title: "你的名字"
description: "硕士研究生 @ 某某大学"
url: "https://你的用户名.github.io"
baseurl: ""

author:
  name: "你的名字"
  avatar: "/images/profile.jpg"   # 把你的头像放在 images/profile.jpg
  bio: "研究方向：XXX | 兴趣：YYY"
  location: "某某大学, 某某城市"
  email: "yourmail@example.com"
  github: "你的GitHub用户名"
  orcid: "0000-0000-0000-0000"   # ORCID ID
  researchgate: "ResearchGate用户名"

# 顶部导航
header_pages:
  - about.md
  - cv.md
