title: "聂平川"
description: "Institute of Computing Technology, Chinese Academy of Sciences"
url: "https://pumpkin0312.github.io"
baseurl: ""

author:
  name: "聂平川"
  avatar: "/images/profile.jpg"   # 把你的头像放在 images/profile.jpg
  bio: "pFind Team"
  location: "No.6 Zhongguancun South Road, Beijing, China, 100190"
  email: "npc2252759540@163.com"
  github: "pumpkin0312"
  orcid: "0000-0000-0000-0000"   # ORCID ID
  researchgate: "ResearchGate用户名"

# 顶部导航
header_pages:
  - about.md
  - cv.md
